### ISSUE TITLE
Why is ArduinoJson missing from search results?

### ISSUE THREAD

**Issue by bblanchon** [arduino-libraries/Arduino_JSON#11]
Hi,

How is it possible that, when one searches "JSON" in [arduino.cc](https://arduino.cc/search?q=json), this library shows up, but [ArduinoJson](https://arduinojson.org/) doesn't?

As far as I can tell, libraries are sorted by GitHub star, and [ArduinoJson](https://arduinojson.org/) has **100x more stars than this library**.

Are you purposely banning my library to promote your own? 🤨

Best regards,
Benoit

PS: also [on Twitter](https://twitter.com/BenoitBlanchon/status/1308850178577895430)

![image](https://user-images.githubusercontent.com/5462433/94063000-c30e7a00-fde7-11ea-9201-f46ebece4d3f.png)

**Comment by matteosuppo** [comment]
Hi, thanks for reporting this issue, sorry if it took time to get a reply, but it had to bubble up to the correct person.

What you're describing definitely looks like a bug: both the library manager and the search engine get their info from the same source: the library index. Your library shows up in the library manager so there's no reason it shouldn't in the search.

We are going to find out what's going wrong, just a bit of patience.

**Comment by bblanchon** [comment]
Thanks a lot, @matteosuppo!

**Comment by matteosuppo** [comment]
Hello again,

We found and fixed the problem: underscores where being stripped, so Arduino_JSON conflicted with ArduinoJSON. Now you can see both of them: https://www.arduino.cc/search?q=json&tab=reference

You may find that your library ArduinoJson is not between the first results. That's because we don't actually sort them by github stars. They aren't sorted at all, actually, it's just an unfortunate coincidence.

**Comment by bblanchon** [comment]
Thank you very much @matteosuppo.
